---
title: "EDS 215 Day 2 Notes"
author: "Scout Leonard"
date: "8/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Helpful Folders for File Organization

- **dist/**: a place to put downloads when you have finished adding new programs to your computer for a project
- **temporary/** a place to put practice files of no importance that you've made for playing around or trying things out 

### Make a buncha folders in bash

`mkdir EDS2{12,22,14,15,23,16}`

`echo mkdir EDS2{12,22,14,15,23,16}` returns what will be generated!

`ls -d eds2??` calls my eds class folders 
*Other ways to do this: 

- `ls -d eds2[2345]`
- `ls -d eds2[2-46]`
- `ls -d eds2[2-46-k]`
- `ls -d eds2[23456]`

### Loops, continued

- **anchor link**: specifies a hyperlink inside of a document or html. (example: links that cut to certain parts of the class agenda html! or like the index bar that links to parts of knitted rmds)

- **{}** wrap a variable in the terminal so you can attach things to the variable and have it recognized still 

- for `chmod` (change mode)
  - `+x` means assign this permission
  - `-x` means take it away 
  - useful for running scripts and removing writing permissions from something you don't want to delete 
  
- Running `>filnname` creates and empty file under the chosen name 

- Running `>>filename` will create a new file (append operator)
  - if that filename already exists, the append operator will add the files 
  
- `set -x` can be run at the top of a script to echo to output for you when you run it 

- `cut` pulls out parts of text 